/**
 * Tests for fee voucher page geometry and packing.
 *
 * There are two documents here with opposite constraints.
 *
 * UNPAID vouchers are printed in bulk and cut apart by hand, so the packing
 * rule has two jobs that pull against each other: fit as many to an A4 sheet as
 * possible (the point of the redesign — a challan used to take a whole page),
 * and never clip a student carrying months of arrears. A clipped voucher
 * understates what a family owes, which is worse than wasting paper.
 *
 * Every bound below is measured, and measured in the WORST case: every voucher
 * in the batch grown to the same height, then rendered and the page count read
 * back. That distinction matters — grid rows size to their own tallest cell, so
 * growing a single challan only stretches its own row. Measured that way,
 * eight-up looked good for eleven lines; grown uniformly it breaks at four.
 *
 *   8 up (4 rows) -> up to 3 lines
 *   6 up (3 rows) -> up to 11 lines
 *   4 up (2 rows) -> up to 18 lines
 *
 * There is no two-up step: two-up is one column of two rows, the same row
 * height as four-up, so it buys width rather than the height that is scarce.
 *
 * PAID receipts have the opposite problem. The school prints them on physical
 * B6 sheets, so the page is not free to grow: it is exactly 125 x 176 mm and
 * the content has to live inside that. These tests read the page box back out
 * of the generated bytes rather than trusting the document definition, because
 * the whole point is what the printer is handed.
 *
 * Run with: npm test
 */
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { perPageFor, renderVouchers, B6_WIDTH_PT, B6_HEIGHT_PT } from './fees.pdf';

/** A voucher carrying `items` charge lines and `dues` brought-forward months. */
const voucher = (items: number, dues = 0) => ({
  items: Array.from({ length: items }, () => ({})) as any,
  previousDues: Array.from({ length: dues }, () => ({})) as any,
  paidAmount: '0',
  cashPaid: '0',
  staffCovered: '0',
});

describe('perPageFor', () => {
  test('always returns 4 vouchers per A4 page (2x2 grid) for unpaid', () => {
    assert.equal(perPageFor(Array.from({ length: 4 }, () => voucher(1))), 4);
    assert.equal(perPageFor(Array.from({ length: 20 }, () => voucher(1))), 4);
    assert.equal(perPageFor([voucher(1, 10)]), 4);
  });

  test('returns 1 voucher per page (full page receipt) for paid receipts', () => {
    const paidVoucher = () => ({ ...voucher(1), paidAmount: '1000', cashPaid: '0', staffCovered: '0' });
    assert.equal(perPageFor([paidVoucher(), paidVoucher()]), 1);
  });

  test('empty batch returns 4-up default', () => {
    assert.equal(perPageFor([]), 4);
  });
});

// ---------------------------------------------------------------------------
// Page geometry, read back from the rendered PDF
// ---------------------------------------------------------------------------

const school = {
  name: 'Test Model School',
  address: 'Main Bypass Road, Garhi Yasin, Shikarpur',
  phone: '0300-1234567',
  email: null,
  logoDataUri: null as string | null,
};

/** A challan shaped as `getChallan` returns one. Paid unless told otherwise. */
function challan(opts: { dues?: number; items?: number; paid?: boolean } = {}): any {
  const items = opts.items ?? 2;
  const dues = opts.dues ?? 1;
  const paid = opts.paid ?? true;
  return {
    id: 'c1',
    challanNo: 'CH-2026-000412',
    studentId: 's1',
    year: 2026,
    month: 8,
    issueDate: '2026-08-01',
    dueDate: '2026-08-10',
    baseAmount: '4500.00',
    discount: '500.00',
    lateFee: '200.00',
    amount: '4200.00',
    paidAmount: paid ? '4200.00' : '0.00',
    cashPaid: paid ? '4200.00' : '0.00',
    staffCovered: '0.00',
    balance: '0.00',
    lastPaymentDate: paid ? '2026-08-05' : null,
    status: paid ? 'PAID' : 'UNPAID',
    isOverdue: false,
    billedToTeacherId: null,
    createdAt: undefined,
    items: Array.from({ length: items }, (_, i) => ({
      id: `i${i}`,
      type: i === 0 ? 'TUITION' : 'TRANSPORT',
      label: i === 0 ? 'Monthly Tuition' : 'Route 2 Transport',
      amount: '1000.00',
    })),
    student: {
      id: 's1',
      name: 'Test Student Name',
      admissionNo: 'STD-833',
      status: 'ACTIVE',
      rollNo: '17',
      className: 'Class 6',
      sectionName: 'Main',
      parentName: 'Test Parent Name',
      parentPhone: '0301-2223344',
    },
    previousDues: Array.from({ length: dues }, (_, i) => ({
      id: `d${i}`,
      challanNo: `CH-2026-0003${i}`,
      year: 2026,
      month: (i % 12) + 1,
      balance: '3200.00',
      staffBilled: false,
    })),
    previousBalance: (3200 * dues).toFixed(2),
    advanceCredit: '0.00',
    totalPayable: (3200 * dues).toFixed(2),
    hasLaterDues: false,
    studentTotalDue: (3200 * dues).toFixed(2),
  };
}

/** Every page's declared media box, in points, as the printer will read it. */
function pageBoxes(pdf: Buffer): { width: number; height: number }[] {
  return [...pdf.toString('latin1').matchAll(/\/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)\s*\]/g)].map((m) => ({
    width: Number(m[1]),
    height: Number(m[2]),
  }));
}

function pageCount(pdf: Buffer): number {
  const counts = [...pdf.toString('latin1').matchAll(/\/Count\s+(\d+)/g)].map((m) => Number(m[1]));
  return counts.length ? Math.max(...counts) : 0;
}

describe('paid receipt page size', () => {
  test('is a native B6 page — exactly 125 x 176 mm', async () => {
    const pdf = await renderVouchers([challan()], school);
    const boxes = pageBoxes(pdf);
    assert.equal(boxes.length, 1);
    // 125 mm and 176 mm at 72 pt/inch, 25.4 mm/inch.
    assert.ok(Math.abs(boxes[0].width - 354.330708) < 0.001, `width ${boxes[0].width}`);
    assert.ok(Math.abs(boxes[0].height - 498.897637) < 0.001, `height ${boxes[0].height}`);
    assert.ok(Math.abs(boxes[0].width - B6_WIDTH_PT) < 0.001);
    assert.ok(Math.abs(boxes[0].height - B6_HEIGHT_PT) < 0.001);
  });

  test('stays B6 whatever the challan carries — the paper cannot change size', async () => {
    for (const dues of [0, 1, 5, 13]) {
      const pdf = await renderVouchers([challan({ dues })], school);
      for (const box of pageBoxes(pdf)) {
        assert.ok(Math.abs(box.width - B6_WIDTH_PT) < 0.001, `dues=${dues} width ${box.width}`);
        assert.ok(Math.abs(box.height - B6_HEIGHT_PT) < 0.001, `dues=${dues} height ${box.height}`);
      }
    }
  });

  test('an ordinary receipt fits on one sheet', async () => {
    for (const dues of [0, 1, 3]) {
      assert.equal(pageCount(await renderVouchers([challan({ dues })], school)), 1, `dues=${dues}`);
    }
  });

  /**
   * The type shrinks to hold a heavy challan on one sheet, but only so far:
   * below roughly 7 pt a parent cannot read what they were charged, and an
   * unreadable receipt is worse than a second sheet. Measured, the boundary is
   * 15 fee rows.
   */
  test('holds up to 15 fee rows on one sheet before flowing to a second', async () => {
    assert.equal(pageCount(await renderVouchers([challan({ dues: 13 })], school)), 1);
    assert.equal(pageCount(await renderVouchers([challan({ dues: 14 })], school)), 2);
  });

  test('gives each receipt in a batch its own sheet', async () => {
    const pdf = await renderVouchers([challan({ dues: 0 }), challan({ dues: 1 })], school);
    assert.equal(pageCount(pdf), 2);
    assert.equal(pageBoxes(pdf).length, 2);
  });

  test('tells a reader not to rescale it when printing', async () => {
    const pdf = (await renderVouchers([challan()], school)).toString('latin1');
    assert.match(pdf, /\/PrintScaling\s*\/None/);
    // An implied CropBox is one a viewer may decide differently about.
    assert.match(pdf, /\/CropBox/);
  });
});

describe('unpaid voucher page size', () => {
  test('is still A4 — the receipt change must not touch the 4-up sheet', async () => {
    const four = Array.from({ length: 4 }, () => challan({ paid: false }));
    const pdf = await renderVouchers(four, school);
    const boxes = pageBoxes(pdf);
    assert.equal(pageCount(pdf), 1, 'four vouchers share one sheet');
    assert.equal(boxes.length, 1);
    assert.ok(Math.abs(boxes[0].width - 595.28) < 0.01, `width ${boxes[0].width}`);
    assert.ok(Math.abs(boxes[0].height - 841.89) < 0.01, `height ${boxes[0].height}`);
  });
});
